"""
DISCLAIMER: This code was NOT written by authors. Code was generated by Claude and edited by project authors.
The actual project was written solely by humans, and any code coming from GenAI is explicitly stated.

Unit tests for gpt.py
Covers: Config, Vocab, MLP, Attention, Transformer, LanguageModel, GPT, in_notebook
Run with: pytest unit_tests.py -v
"""

import pytest
import torch
import torch.nn as nn
import os
import json

from master_utility import (
    Config,
    Vocab,
    MLP,
    Attention,
    Transformer,
    LanguageModel,
    GPT,
    in_notebook,
)

# ---------------------------------------------------------------------------
# Shared constants & fixtures
# ---------------------------------------------------------------------------

SAMPLE_TEXT = "the quick brown fox jumps over the lazy dog " * 50


@pytest.fixture
def sample_config():
    return Config(d_model=16, d_vocab=50, d_hidden=32, max_seq_len=32, n_layers=2)


@pytest.fixture
def sample_vocab():
    v = Vocab()
    v.update_dictionaries(SAMPLE_TEXT.split())
    return v


@pytest.fixture
def trained_gpt():
    gpt = GPT()
    gpt.train(n_iter=10, plain_text=SAMPLE_TEXT * 10, update=0, plot=False)
    return gpt


# ===========================================================================
# Config
# ===========================================================================

class TestConfig:
    def test_all_fields_stored(self):
        cfg = Config(d_model=128, d_vocab=100, d_hidden=256, max_seq_len=64, n_layers=4)
        assert cfg.d_model == 128
        assert cfg.d_vocab == 100
        assert cfg.d_hidden == 256
        assert cfg.max_seq_len == 64
        assert cfg.n_layers == 4

    def test_positional_construction(self):
        cfg = Config(8, 10, 16, 20, 2)
        assert cfg.d_model == 8
        assert cfg.n_layers == 2

    def test_fields_are_mutable(self):
        cfg = Config(8, 10, 16, 20, 2)
        cfg.d_vocab = 999
        assert cfg.d_vocab == 999


# ===========================================================================
# Vocab - __init__ and get_text
# ===========================================================================

class TestVocabInit:
    def test_blank_vocab_zero_tokens(self):
        v = Vocab()
        assert v.d_vocab == 0
        assert v.forward_dict == {}
        assert v.backward_dict == {}

    def test_vocab_from_file_populates_dicts(self, tmp_path):
        fpath = tmp_path / "sample.txt"
        fpath.write_text(SAMPLE_TEXT, encoding="utf-8")
        v = Vocab(str(fpath))
        assert v.d_vocab > 0
        assert "the" in v.forward_dict
        assert "fox" in v.forward_dict

    def test_get_text_returns_full_string(self, tmp_path):
        fpath = tmp_path / "t.txt"
        fpath.write_text("hello world", encoding="utf-8")
        v = Vocab()
        text = v.get_text(str(fpath))
        assert isinstance(text, str)
        assert "hello" in text

    def test_get_text_missing_file_raises(self):
        v = Vocab()
        with pytest.raises(Exception):
            v.get_text("no_such_file_xyz.txt")


# ===========================================================================
# Vocab - get_token_arr
# ===========================================================================

class TestVocabGetTokenArr:
    def test_lowercasing(self):
        v = Vocab()
        tokens = v.get_token_arr("UPPER lower MiXeD")
        assert all(t == t.lower() for t in tokens)

    def test_basic_split(self):
        v = Vocab()
        tokens = v.get_token_arr("hello world")
        assert tokens == ["hello", "world"]

    def test_special_chars_stripped(self):
        v = Vocab()
        tokens = v.get_token_arr("hello! world@ #test")
        for tok in tokens:
            assert all(c.isalnum() or c in ".? \n" for c in tok)

    def test_empty_string_returns_empty_list(self):
        v = Vocab()
        assert v.get_token_arr("") == []

    def test_numbers_preserved(self):
        v = Vocab()
        tokens = v.get_token_arr("word 42 another 007")
        assert "42" in tokens
        assert "007" in tokens

    def test_newlines_handled(self):
        v = Vocab()
        tokens = v.get_token_arr("hello\nworld")
        assert "hello" in tokens
        assert "world" in tokens


# ===========================================================================
# Vocab - set_dictionaries / update_dictionaries
# ===========================================================================

class TestVocabDictionaries:
    def test_unique_ids(self, sample_vocab):
        ids = list(sample_vocab.forward_dict.values())
        assert len(ids) == len(set(ids))

    def test_forward_backward_roundtrip(self, sample_vocab):
        for token, idx in sample_vocab.forward_dict.items():
            assert sample_vocab.backward_dict[idx] == token

    def test_d_vocab_matches_forward_dict_size(self, sample_vocab):
        assert sample_vocab.d_vocab == len(sample_vocab.forward_dict)

    def test_update_adds_new_tokens(self, sample_vocab):
        before = sample_vocab.d_vocab
        sample_vocab.update_dictionaries(["newtoken1", "newtoken2"])
        assert sample_vocab.d_vocab == before + 2

    def test_update_ignores_existing_tokens(self, sample_vocab):
        before = sample_vocab.d_vocab
        sample_vocab.update_dictionaries(["the"])
        assert sample_vocab.d_vocab == before

    def test_ids_contiguous_after_update(self, sample_vocab):
        sample_vocab.update_dictionaries(["brandnewtoken"])
        all_ids = sorted(sample_vocab.forward_dict.values())
        assert all_ids == list(range(sample_vocab.d_vocab))


# ===========================================================================
# Vocab - add_text
# ===========================================================================

class TestVocabAddText:
    def test_plain_text_expands_vocab(self, sample_vocab):
        before = sample_vocab.d_vocab
        sample_vocab.add_text(plain_text="supernova pulsar quasar")
        assert sample_vocab.d_vocab > before

    def test_both_args_prints_error(self, sample_vocab, capsys):
        sample_vocab.add_text(text_file="x.txt", plain_text="hello")
        assert "ERROR" in capsys.readouterr().out

    def test_no_args_prints_error(self, sample_vocab, capsys):
        sample_vocab.add_text()
        assert "ERROR" in capsys.readouterr().out

    def test_missing_file_prints_error(self, sample_vocab, capsys):
        sample_vocab.add_text(text_file="nonexistent.txt")
        assert "ERROR" in capsys.readouterr().out

    def test_from_file_expands_vocab(self, sample_vocab, tmp_path):
        fpath = tmp_path / "extra.txt"
        fpath.write_text("xyzzyworda xyzzywordb", encoding="utf-8")
        before = sample_vocab.d_vocab
        sample_vocab.add_text(text_file=str(fpath))
        assert sample_vocab.d_vocab > before

    def test_no_duplicate_tokens_from_add(self, sample_vocab):
        before = sample_vocab.d_vocab
        sample_vocab.add_text(plain_text=SAMPLE_TEXT)
        assert sample_vocab.d_vocab == before


# ===========================================================================
# Vocab - get_token_ids
# ===========================================================================

class TestVocabGetTokenIds:
    def test_known_tokens_return_ints(self, sample_vocab):
        ids = sample_vocab.get_token_ids(["the", "fox"])
        assert len(ids) == 2
        assert all(isinstance(i, int) for i in ids)

    def test_unknown_token_fail_on_unknown_true(self, sample_vocab, capsys):
        result = sample_vocab.get_token_ids(["xyzzyunknown999"])
        assert result == []
        assert "ERROR" in capsys.readouterr().out

    def test_unknown_token_fail_on_unknown_false(self, sample_vocab):
        result = sample_vocab.get_token_ids(
            ["the", "xyzzyunknown999", "fox"], fail_on_unknown=False
        )
        assert len(result) == 2

    def test_empty_list_returns_empty(self, sample_vocab):
        assert sample_vocab.get_token_ids([]) == []

    def test_ids_map_back_to_tokens(self, sample_vocab):
        tokens = ["the", "fox"]
        ids = sample_vocab.get_token_ids(tokens)
        for tok, id_ in zip(tokens, ids):
            assert sample_vocab.backward_dict[id_] == tok


# ===========================================================================
# Vocab - get_token_from_id
# ===========================================================================

class TestVocabGetTokenFromId:
    def test_valid_id_returns_string(self, sample_vocab):
        token = sample_vocab.get_token_from_id(0)
        assert isinstance(token, str)
        assert token != "ERROR"

    def test_invalid_id_returns_error(self, sample_vocab, capsys):
        result = sample_vocab.get_token_from_id(99999)
        assert result == "ERROR"
        assert "ERROR" in capsys.readouterr().out

    def test_roundtrip_token_to_id_and_back(self, sample_vocab):
        token = "the"
        id_ = sample_vocab.forward_dict[token]
        assert sample_vocab.get_token_from_id(id_) == token


# ===========================================================================
# Vocab - get_prompt_token_ids
# ===========================================================================

class TestVocabGetPromptTokenIds:
    def test_returns_list_of_ints(self, sample_vocab):
        ids = sample_vocab.get_prompt_token_ids("the fox")
        assert isinstance(ids, list)
        assert all(isinstance(i, int) for i in ids)

    def test_unknown_tokens_silently_skipped(self, sample_vocab):
        ids = sample_vocab.get_prompt_token_ids("the xyzzyNOTAWORD fox")
        assert len(ids) == 2

    def test_empty_prompt_returns_empty(self, sample_vocab):
        ids = sample_vocab.get_prompt_token_ids("")
        assert ids == []


# ===========================================================================
# Vocab - save / get_vocab_from (load)
# ===========================================================================

class TestVocabSaveLoad:
    def test_save_creates_file(self, sample_vocab, tmp_path):
        fpath = str(tmp_path / "test.vcb")
        sample_vocab.save(fpath)
        assert os.path.exists(fpath)

    def test_save_produces_valid_json(self, sample_vocab, tmp_path):
        fpath = str(tmp_path / "test.vcb")
        sample_vocab.save(fpath)
        with open(fpath, "r", encoding="utf-8") as f:
            data = json.load(f)
        assert "backward_dict" in data
        assert "d_vocab" in data

    def test_load_restores_d_vocab(self, sample_vocab, tmp_path):
        fpath = str(tmp_path / "test.vcb")
        sample_vocab.save(fpath)
        loaded = Vocab.get_vocab_from(fpath)
        assert loaded.d_vocab == sample_vocab.d_vocab

    def test_load_restores_forward_dict(self, sample_vocab, tmp_path):
        fpath = str(tmp_path / "test.vcb")
        sample_vocab.save(fpath)
        loaded = Vocab.get_vocab_from(fpath)
        assert loaded.forward_dict == sample_vocab.forward_dict

    def test_load_restores_backward_dict(self, sample_vocab, tmp_path):
        fpath = str(tmp_path / "test.vcb")
        sample_vocab.save(fpath)
        loaded = Vocab.get_vocab_from(fpath)
        assert loaded.backward_dict == sample_vocab.backward_dict

    def test_load_missing_file_raises(self):
        with pytest.raises(Exception):
            Vocab.get_vocab_from("does_not_exist_xyz.vcb")

    def test_loaded_vocab_can_lookup_tokens(self, sample_vocab, tmp_path):
        fpath = str(tmp_path / "test.vcb")
        sample_vocab.save(fpath)
        loaded = Vocab.get_vocab_from(fpath)
        assert loaded.get_token_from_id(0) != "ERROR"


# ===========================================================================
# MLP
# ===========================================================================

class TestMLP:
    def test_output_shape_preserved(self, sample_config):
        mlp = MLP(sample_config)
        x = torch.randn(10, sample_config.d_model)
        assert mlp(x).shape == x.shape

    def test_single_row_input(self, sample_config):
        mlp = MLP(sample_config)
        x = torch.randn(1, sample_config.d_model)
        assert mlp(x).shape == (1, sample_config.d_model)

    def test_output_is_tensor(self, sample_config):
        mlp = MLP(sample_config)
        assert isinstance(mlp(torch.randn(5, sample_config.d_model)), torch.Tensor)

    def test_has_trainable_parameters(self, sample_config):
        mlp = MLP(sample_config)
        assert len(list(mlp.parameters())) > 0

    def test_gradient_flows_to_input(self, sample_config):
        mlp = MLP(sample_config)
        x = torch.randn(4, sample_config.d_model, requires_grad=True)
        mlp(x).sum().backward()
        assert x.grad is not None

    def test_fc1_dimensions(self, sample_config):
        mlp = MLP(sample_config)
        assert mlp.fc1.in_features == sample_config.d_model
        assert mlp.fc1.out_features == sample_config.d_hidden

    def test_fc2_dimensions(self, sample_config):
        mlp = MLP(sample_config)
        assert mlp.fc2.in_features == sample_config.d_hidden
        assert mlp.fc2.out_features == sample_config.d_model


# ===========================================================================
# Attention
# ===========================================================================

class TestAttention:
    def test_output_shape(self, sample_config):
        attn = Attention(sample_config)
        T = 8
        x = torch.randn(T, sample_config.d_model)
        assert attn(x).shape == (T, sample_config.d_model)

    def test_single_token(self, sample_config):
        attn = Attention(sample_config)
        x = torch.randn(1, sample_config.d_model)
        assert attn(x).shape == (1, sample_config.d_model)

    def test_mask_buffer_registered(self, sample_config):
        attn = Attention(sample_config)
        assert hasattr(attn, "M")
        assert attn.M.shape == (sample_config.max_seq_len, sample_config.max_seq_len)

    def test_mask_upper_triangle_is_neg_inf(self, sample_config):
        attn = Attention(sample_config)
        assert attn.M[0, 1] == -float("inf")
        assert attn.M[1, 2] == -float("inf")

    def test_mask_lower_triangle_and_diagonal_is_zero(self, sample_config):
        attn = Attention(sample_config)
        assert attn.M[1, 0] == 0.0
        assert attn.M[2, 0] == 0.0
        assert attn.M[0, 0] == 0.0

    def test_wqk_parameter_exists(self, sample_config):
        attn = Attention(sample_config)
        param_names = [n for n, _ in attn.named_parameters()]
        assert "Wqk" in param_names

    def test_wov_parameter_exists(self, sample_config):
        attn = Attention(sample_config)
        param_names = [n for n, _ in attn.named_parameters()]
        assert "Wov" in param_names

    def test_wqk_shape(self, sample_config):
        attn = Attention(sample_config)
        assert attn.Wqk.shape == (sample_config.d_model, sample_config.d_model)

    def test_wov_shape(self, sample_config):
        attn = Attention(sample_config)
        assert attn.Wov.shape == (sample_config.d_model, sample_config.d_model)


# ===========================================================================
# Transformer
# ===========================================================================

class TestTransformer:
    def test_output_shape(self, sample_config):
        tf = Transformer(sample_config)
        x = torch.randn(6, sample_config.d_model)
        assert tf(x).shape == (6, sample_config.d_model)

    def test_single_token(self, sample_config):
        tf = Transformer(sample_config)
        x = torch.randn(1, sample_config.d_model)
        assert tf(x).shape == (1, sample_config.d_model)

    def test_has_mlp_layer_norm(self, sample_config):
        tf = Transformer(sample_config)
        assert isinstance(tf.mlp_normalizer, nn.LayerNorm)

    def test_has_attn_layer_norm(self, sample_config):
        tf = Transformer(sample_config)
        assert isinstance(tf.attn_normalizer, nn.LayerNorm)

    def test_contains_attention_module(self, sample_config):
        tf = Transformer(sample_config)
        assert isinstance(tf.attn, Attention)

    def test_contains_mlp_module(self, sample_config):
        tf = Transformer(sample_config)
        assert isinstance(tf.mlp, MLP)

    def test_zero_input_produces_valid_output(self, sample_config):
        tf = Transformer(sample_config)
        x = torch.zeros(4, sample_config.d_model)
        out = tf(x)
        assert not torch.isnan(out).any()


# ===========================================================================
# LanguageModel
# ===========================================================================

class TestLanguageModel:
    def test_logit_shape(self, sample_config):
        lm = LanguageModel(sample_config)
        x = torch.randint(0, sample_config.d_vocab, (10,))
        assert lm(x).shape == (10, sample_config.d_vocab)

    def test_single_token_input(self, sample_config):
        lm = LanguageModel(sample_config)
        x = torch.randint(0, sample_config.d_vocab, (1,))
        assert lm(x).shape == (1, sample_config.d_vocab)

    def test_embedding_num_embeddings(self, sample_config):
        lm = LanguageModel(sample_config)
        assert lm.embedding.num_embeddings == sample_config.d_vocab

    def test_embedding_dim(self, sample_config):
        lm = LanguageModel(sample_config)
        assert lm.embedding.embedding_dim == sample_config.d_model

    def test_positional_embedding_size(self, sample_config):
        lm = LanguageModel(sample_config)
        assert lm.positional_embedding.num_embeddings == sample_config.max_seq_len

    def test_n_transformer_blocks(self, sample_config):
        lm = LanguageModel(sample_config)
        assert len(lm.tbs) == sample_config.n_layers

    def test_lm_head_output_features(self, sample_config):
        lm = LanguageModel(sample_config)
        assert lm.lm_head.out_features == sample_config.d_vocab

    def test_gradient_propagates(self, sample_config):
        lm = LanguageModel(sample_config)
        x = torch.randint(0, sample_config.d_vocab, (5,))
        lm(x).sum().backward()
        grads = [p.grad for p in lm.parameters() if p.grad is not None]
        assert len(grads) > 0

    def test_no_nans_in_output(self, sample_config):
        lm = LanguageModel(sample_config)
        x = torch.randint(0, sample_config.d_vocab, (8,))
        out = lm(x)
        assert not torch.isnan(out).any()


# ===========================================================================
# GPT - __init__
# ===========================================================================

class TestGPTInit:
    def test_has_vocab(self):
        assert isinstance(GPT().vocab, Vocab)

    def test_has_config(self):
        assert isinstance(GPT().config, Config)

    def test_has_model(self):
        assert isinstance(GPT().model, LanguageModel)


# ===========================================================================
# GPT - update_vocab_with_tokens
# ===========================================================================

class TestGPTUpdateVocabWithTokens:
    def test_new_tokens_added(self):
        gpt = GPT()
        gpt.update_vocab_with_tokens(["alpha", "beta", "gamma"])
        assert gpt.vocab.d_vocab == 3

    def test_embedding_resized(self):
        gpt = GPT()
        gpt.update_vocab_with_tokens(["alpha", "beta", "gamma"])
        assert gpt.model.embedding.num_embeddings == 3

    def test_lm_head_resized(self):
        gpt = GPT()
        gpt.update_vocab_with_tokens(["x", "y", "z"])
        assert gpt.model.lm_head.out_features == 3

    def test_duplicates_not_added(self):
        gpt = GPT()
        gpt.update_vocab_with_tokens(["alpha", "beta"])
        gpt.update_vocab_with_tokens(["alpha"])
        assert gpt.vocab.d_vocab == 2

    def test_config_d_vocab_updated(self):
        gpt = GPT()
        gpt.update_vocab_with_tokens(["a", "b"])
        assert gpt.config.d_vocab == 2


# ===========================================================================
# GPT - refresh_vocab_dim
# ===========================================================================

class TestGPTRefreshVocabDim:
    def test_config_updated(self):
        gpt = GPT()
        gpt.vocab.update_dictionaries(["one", "two", "three"])
        gpt.refresh_vocab_dim()
        assert gpt.config.d_vocab == 3

    def test_embedding_updated(self):
        gpt = GPT()
        gpt.vocab.update_dictionaries(["one", "two", "three"])
        gpt.refresh_vocab_dim()
        assert gpt.model.embedding.num_embeddings == 3

    def test_lm_head_updated(self):
        gpt = GPT()
        gpt.vocab.update_dictionaries(["one", "two", "three"])
        gpt.refresh_vocab_dim()
        assert gpt.model.lm_head.out_features == 3


# ===========================================================================
# GPT - train
# ===========================================================================

class TestGPTTrain:
    def test_train_plain_text(self):
        gpt = GPT()
        gpt.train(n_iter=5, plain_text=SAMPLE_TEXT * 10, update=0, plot=False)
        assert gpt.vocab.d_vocab > 0

    def test_train_populates_vocab(self):
        gpt = GPT()
        gpt.train(n_iter=5, plain_text=SAMPLE_TEXT * 10, update=0, plot=False)
        assert "fox" in gpt.vocab.forward_dict

    def test_train_no_args_error(self, capsys):
        gpt = GPT()
        gpt.train(n_iter=2, update=0, plot=False)
        assert "ERROR" in capsys.readouterr().out

    def test_train_both_args_error(self, capsys):
        gpt = GPT()
        gpt.train(n_iter=2, plain_text="hi", text_file="x.txt", update=0, plot=False)
        assert "ERROR" in capsys.readouterr().out

    def test_train_missing_file_error(self, capsys):
        gpt = GPT()
        gpt.train(n_iter=2, text_file="nofile.txt", update=0, plot=False)
        assert "ERROR" in capsys.readouterr().out

    def test_train_from_file(self, tmp_path):
        fpath = tmp_path / "train.txt"
        fpath.write_text(SAMPLE_TEXT * 10, encoding="utf-8")
        gpt = GPT()
        gpt.train(n_iter=5, text_file=str(fpath), update=0, plot=False)
        assert gpt.vocab.d_vocab > 0

    def test_train_sample_prompt_printed(self, capsys):
        gpt = GPT()
        gpt.train(
            n_iter=5,
            plain_text=SAMPLE_TEXT * 10,
            update=0,
            plot=False,
            sample_prompt="the fox",
        )
        assert "the fox" in capsys.readouterr().out

    def test_train_update_interval_prints(self, capsys):
        gpt = GPT()
        gpt.train(n_iter=10, plain_text=SAMPLE_TEXT * 10, update=5, plot=False)
        assert "Step" in capsys.readouterr().out


# ===========================================================================
# GPT - query
# ===========================================================================

class TestGPTQuery:
    def test_returns_string(self, trained_gpt):
        assert isinstance(trained_gpt.query("the fox", out_tokens=3), str)

    def test_multinomial_nonempty(self, trained_gpt):
        result = trained_gpt.query("the fox", out_tokens=5, sampling="multinomial")
        assert len(result.strip()) > 0

    def test_greedy_nonempty(self, trained_gpt):
        result = trained_gpt.query("the fox", out_tokens=5, sampling="greedy")
        assert len(result.strip()) > 0

    def test_invalid_sampling_returns_empty(self, trained_gpt, capsys):
        result = trained_gpt.query("the fox", sampling="beam_search")
        assert result == ""
        assert "ERROR" in capsys.readouterr().out

    def test_correct_token_count(self, trained_gpt):
        out_tokens = 4
        result = trained_gpt.query("the fox", out_tokens=out_tokens)
        assert len(result.strip().split()) == out_tokens

    def test_to_print_true_prints_output(self, trained_gpt, capsys):
        trained_gpt.query("the fox", out_tokens=3, to_print=True)
        assert len(capsys.readouterr().out.strip()) > 0

    def test_to_print_false_no_stdout(self, trained_gpt, capsys):
        trained_gpt.query("the fox", out_tokens=3, to_print=False)
        assert capsys.readouterr().out == ""

    def test_empty_prompt_handled_gracefully(self, trained_gpt):
        # Should not raise; must return a string
        result = trained_gpt.query("", out_tokens=3)
        assert isinstance(result, str)

    def test_greedy_is_deterministic(self, trained_gpt):
        r1 = trained_gpt.query("the fox", out_tokens=5, sampling="greedy")
        r2 = trained_gpt.query("the fox", out_tokens=5, sampling="greedy")
        assert r1 == r2


# ===========================================================================
# GPT - save / load_gpt_from
# ===========================================================================

class TestGPTSaveLoad:
    """
    Each test changes cwd into a tmp directory so save/load use isolated paths.
    """

    def _make_trained_gpt(self):
        gpt = GPT()
        gpt.train(n_iter=5, plain_text=SAMPLE_TEXT * 10, update=0, plot=False)
        return gpt

    def test_save_creates_mdl(self, tmp_path):
        gpt = self._make_trained_gpt()
        original = os.getcwd()
        os.chdir(tmp_path)
        os.makedirs("models", exist_ok=True)
        gpt.save("mymodel")
        assert os.path.exists("models/mymodel.mdl")
        os.chdir(original)

    def test_save_creates_vcb(self, tmp_path):
        gpt = self._make_trained_gpt()
        original = os.getcwd()
        os.chdir(tmp_path)
        os.makedirs("models", exist_ok=True)
        gpt.save("mymodel")
        assert os.path.exists("models/mymodel.vcb")
        os.chdir(original)

    def test_save_default_name_creates_both_files(self, tmp_path):
        gpt = self._make_trained_gpt()
        original = os.getcwd()
        os.chdir(tmp_path)
        os.makedirs("models", exist_ok=True)
        gpt.save()
        files = os.listdir("models")
        assert any(f.endswith(".mdl") for f in files)
        assert any(f.endswith(".vcb") for f in files)
        os.chdir(original)

    def test_load_restores_vocab(self, tmp_path):
        gpt = self._make_trained_gpt()
        original = os.getcwd()
        os.chdir(tmp_path)
        os.makedirs("models", exist_ok=True)
        gpt.save("mymodel")
        loaded = GPT.load_gpt_from("mymodel")
        assert loaded.vocab.d_vocab == gpt.vocab.d_vocab
        assert loaded.vocab.forward_dict == gpt.vocab.forward_dict
        os.chdir(original)

    def test_load_restores_model_weights(self, tmp_path):
        gpt = self._make_trained_gpt()
        original = os.getcwd()
        os.chdir(tmp_path)
        os.makedirs("models", exist_ok=True)
        gpt.save("mymodel")
        loaded = GPT.load_gpt_from("mymodel")
        p_orig = next(iter(gpt.model.parameters()))
        p_load = next(iter(loaded.model.parameters()))
        assert torch.allclose(p_orig, p_load)
        os.chdir(original)

    def test_load_missing_raises(self):
        with pytest.raises(Exception):
            GPT.load_gpt_from("does_not_exist_xyzabc")


# ===========================================================================
# in_notebook
# ===========================================================================

class TestInNotebook:
    def test_returns_bool(self):
        assert isinstance(in_notebook(), bool)

    def test_false_in_pytest(self):
        # pytest does not run inside a ZMQInteractiveShell
        assert in_notebook() is False